version: '3.7'
services:
  hydra2:
    image: linuxserver/hydra2:latest
    container_name: hydra2
    hostname: hydra2
    restart: unless-stopped
    volumes:
      - ../Data/config:/config
      - ../Data/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.hydra2.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.hydra2.entrypoints=web-secure"
      - "traefik.http.routers.hydra2.middlewares=default-headers@file"
      - "traefik.http.routers.hydra2.service=hydra2"
      - "traefik.http.routers.hydra2.tls=true"
      - "traefik.http.services.hydra2.loadbalancer.server.port=5076" # Proxied Port
